// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { SidebarProvider } from '@/components/ui/sidebar'
import { AppSidebar } from './_components/side-nav'
import { Header } from './_components/header'

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <div className='w-full'>
        <Header />
        <main className='container mx-auto pt-12 min-h-screen'>
          <div className='flex gap-8'>
            <div className='w-full'> {children}</div>
          </div>
        </main>
      </div>
    </SidebarProvider>
  )
}
